name: Nebius Qwen Inference (Drive ZIP + existing scripts)

on:
  workflow_dispatch:
    inputs:
      drive_zip_file_id:
        description: "Google Drive FILE ID of semi-aves.zip (e.g., 16a9dvGMQwypqfAQ0vRtfMQzb7Aa7L2el)"
        required: true
      api_model:
        description: "Nebius model name"
        required: false
        default: "Qwen/Qwen2.5-VL-72B-Instruct"
      api_base:
        description: "Nebius OpenAI-compatible base URL"
        required: false
        default: "https://api.studio.nebius.com/v1/"

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 350

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          pip install gdown

      - name: Install unzip
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip

      - name: Download dataset ZIP and unzip
        run: |
          set -euxo pipefail
          mkdir -p /tmp/dataset
          gdown "https://drive.google.com/uc?id=${{ github.event.inputs.drive_zip_file_id }}" -O /tmp/dataset/semi-aves.zip
          unzip -q /tmp/dataset/semi-aves.zip -d /tmp/dataset
          echo "After unzip:"
          find /tmp/dataset -maxdepth 2 -type d | sed 's/^/  /' | head -n 50

      - name: Expose dataset at ./datasets/semi-aves (as expected by wrapper)
        run: |
          mkdir -p datasets
          if [ -d /tmp/dataset/semi-aves ]; then
            ln -s /tmp/dataset/semi-aves datasets/semi-aves
          else
            CAND="$(find /tmp/dataset -maxdepth 2 -type d -name semi-aves | head -n1)"
            if [ -n "$CAND" ]; then
              ln -s "$CAND" datasets/semi-aves
            else
              echo "ERROR: Could not find 'semi-aves' folder in /tmp/dataset" >&2
              exit 1
            fi
          fi
          ls -la datasets

      - name: Provide .env for run_qwen.sh (NEBIUS_API_KEY)
        env:
          NEBIUS_API_KEY: ${{ secrets.NEBIUS_API_KEY }}
        run: |
          echo "NEBIUS_API_KEY=${NEBIUS_API_KEY}" > .env
          echo "NEBIUS_API_BASE=${{ github.event.inputs.api_base }}" >> .env
          echo ".env created at repo root"

      - name: Make scripts executable
        run: |
          chmod +x mllm-inference/semi-aves/scripts/run_nebius_72b.sh
          chmod +x mllm-inference/semi-aves/scripts/run_qwen.sh

      - name: Run your wrapper (which calls run_qwen.sh)
        run: |
          mllm-inference/semi-aves/scripts/run_nebius_72b.sh

      - name: Collect & upload outputs
        run: |
          mkdir -p outputs
          find . -type f \( -name "*.csv" -o -name "*.log" -o -name "*.txt" \) | sed 's/^/  /'
          cp -r mllm-inference/semi-aves/mllm_output/*.csv outputs/ 2>/dev/null || true
          cp -r mllm-inference/semi-aves/mllm_output/*.txt outputs/ 2>/dev/null || true

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: qwen-results
          path: outputs/
          if-no-files-found: warn
